[supervisord]
nodaemon = true
user = root
pidfile = /var/run/supervisord.pid

[program:server]
autostart = true
autorestart = false
stopwaitsecs = 8
startsecs = 3
command = python backend/server.py
stopsignal=INT
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
redirect_stderr = true

[program:grabber]
autostart = true
autorestart = false
stopwaitsecs = 8
startsecs = 3
command = python backend/grabber.py
stopsignal=TERM
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
redirect_stderr = true

[eventlistener:processes]
command=bash -c "printf 'READY\n' && while read -r line; do kill -s SIGTERM 1; exit 1; done < /dev/stdin"
events=PROCESS_STATE_STOPPED,PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
